CFLAGS=-ansi -pedantic -Wall -Werror -ggdb -O0 -D_POSIX_SOURCE -I"../.."
LDLIBS=-lreadline

ALL: compile_c_test

c_test: c_test.c
c_submenu: c_submenu.c

compile_c_test: c_test
compile_c_submenu: c_submenu
